name: Test
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  pull-requests: write

jobs:
  test-check:
    name: runner / textlint (github-check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: textlint-github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          textlint_flags: "doc/**"

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / textlint (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: textlint-github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          textlint_flags: "doc/**"

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / textlint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: textlint-github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: "doc/**"
