name: run-textlint

on:
    push:
      branches:
        - main_
    pull_request:
      branches:
        - main_

jobs:
  run-textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup node with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install textlint
        run: >
          npm install --save-dev
          textlint
          textlint-rule-preset-smarthr
          textlint-rule-prh
          textlint-filter-rule-allowlist
          textlint-rule-preset-ja-technical-writing
      
      - name: Install dependent module
        run: npm install

      - name: Execute textlint
        continue-on-error: true
        run: npx textlint "index.md"