name: Generate Marp PDF and PowerPoint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Convert Markdown into HTML and PDF
      uses: KoharaKazuya/marp-cli-action@v4

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./examples

